export const environment = {
  production: true, // Stage should behave like production
  COOKIE_DOMAIN: '%COOKIE_DOMAIN%',
  GOOGLE_ANALYTICS_ID: '%GOOGLE_ANALYTICS_ID%',
  GOOGLE_MAPS_API_KEY: '%GOOGLE_MAPS_API_KEY%',
  CONTRIBUTION_FORM_ENDPOINT: '%CONTRIBUTION_FORM_ENDPOINT%',
  CONTRIBUTION_FORM_RECIPIENT: '%CONTRIBUTION_FORM_RECIPIENT%',
  SENTRY_DSN_PUBLIC: '%SENTRY_DSN_PUBLIC%'
};
