version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

executors:
  shared-executor:
    docker:
      - image: circleci/node:10.9.0-stretch-browsers
    working_directory: ~/repo

jobs:
  build:
    executor: shared-executor

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install packages
          command: yarn install && yarn install --dev

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Inject environment variables
          command: ./.circleci/replace-envs

      - run:
          name: Build the source (dev)
          command: yarn build

      - persist_to_workspace:
            root: .
            paths:
                - .

  test:
    executor: shared-executor

    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint the source
          command: yarn lint

      - run:
          name: Run the tests
          command: yarn test-ci

      - store_artifacts:
          path: ./build_artifacts

      - store_test_results:
          path: ./build_artifacts/test-results

      - codecov/upload:
          file: ./build_artifacts/coverage/lcov.info

  deploy:
    executor: shared-executor

    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build the source (prod)
          command: yarn build --prod

workflows:
  version: 2

  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - test:
          requires:
            - build

  build_test_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
