#!/usr/bin/env bash

# 1. Create the base environment config file that Angular-cli expects
if [ ! -f $HOME/repo/src/environments/environment.ts ]; then
    cp $HOME/repo/src/environments/environment.ts.dist $HOME/repo/src/environments/environment.ts
fi

# 2. Inject CI environment variables into the 'test-ci' environment config file.
# IMPORTANT: --silent switch avoids exposing environment variables through CI logs
node ./node_modules/.bin/replace --silent '%COOKIE_DOMAIN%'                ${PROD_COOKIE_DOMAIN}                $HOME/repo/src/environments/environment.prod.ts
node ./node_modules/.bin/replace --silent '%GOOGLE_ANALYTICS_ID%'          ${PROD_GOOGLE_ANALYTICS_ID}          $HOME/repo/src/environments/environment.prod.ts
node ./node_modules/.bin/replace --silent '%GOOGLE_MAPS_API_KEY%'          ${PROD_GOOGLE_MAPS_API_KEY}          $HOME/repo/src/environments/environment.prod.ts
node ./node_modules/.bin/replace --silent '%CONTRIBUTION_FORM_ENDPOINT%'   ${PROD_CONTRIBUTION_FORM_ENDPOINT}   $HOME/repo/src/environments/environment.prod.ts
node ./node_modules/.bin/replace --silent '%CONTRIBUTION_FORM_RECIPIENT%'  ${PROD_CONTRIBUTION_FORM_RECIPIENT}  $HOME/repo/src/environments/environment.prod.ts
