#!/usr/bin/env bash

# 1. Create the base environment config file that Angular-cli expects
if [ ! -f $HOME/repo/src/environments/environment.ts ]; then
    cp $HOME/repo/src/environments/environment.ts.dist $HOME/repo/src/environments/environment.ts
fi


# 2. Inject CI environment variables into the 'test-ci' environment config file.
# IMPORTANT: --silent switch avoids exposing environment variables through CI logs
node ./node_modules/.bin/replace --silent '%COOKIE_DOMAIN%'                ${TEST_CI_COOKIE_DOMAIN}                $HOME/repo/src/environments/environment.test-ci.ts
node ./node_modules/.bin/replace --silent '%GOOGLE_ANALYTICS_ID%'          ${TEST_CI_GOOGLE_ANALYTICS_ID}          $HOME/repo/src/environments/environment.test-ci.ts
node ./node_modules/.bin/replace --silent '%GOOGLE_MAPS_API_KEY%'          ${TEST_CI_GOOGLE_MAPS_API_KEY}          $HOME/repo/src/environments/environment.test-ci.ts
node ./node_modules/.bin/replace --silent '%CONTRIBUTION_FORM_ENDPOINT%'   ${TEST_CI_CONTRIBUTION_FORM_ENDPOINT}   $HOME/repo/src/environments/environment.test-ci.ts
node ./node_modules/.bin/replace --silent '%CONTRIBUTION_FORM_RECIPIENT%'  ${TEST_CI_CONTRIBUTION_FORM_RECIPIENT}  $HOME/repo/src/environments/environment.test-ci.ts
